from internal.dialog.main_menu.helpers.error_flags_manager import ErrorFlagsManager
from internal.dialog.main_menu.helpers.navigation import NavigationManager
from internal.dialog.main_menu.helpers.validation import ValidationService